"""followers

Revision ID: 785c2b52c6d6
Revises: dbb395fb85d7
Create Date: 2018-08-12 11:48:02.193318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785c2b52c6d6'
down_revision = 'dbb395fb85d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
